---
swagger: '2.0'
host: localhost:8000
info:
  version: 1.0.0
  title: bankgoji
paths:
  /banks:
    get:
      responses:
        200:
          description: Return all banks
          schema:
            type: object
            additionalProperties:
              $ref: Bank
              
  /banks/{id}:
    get:
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of bank to fetch
          required: true
          type: string
      responses:
        200:
          description: Return a bank
          schema:
            $ref: Bank
  
  /banks/{id}/accounts:
    get:
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of bank to fetch
          required: true
          type: string
      responses:
        200:
          description: Return accounts for a given  bank
          schema:
            type: array
            $item: 
              $ref: Account
  
  /banks/{bank_id}/accounts/{account_id}:
    get:
      produces:
        - application/json
      parameters:
        - name: bank_id
          in: path
          description: ID of bank to fetch
          required: true
          type: string
        - name: account_id
          in: path
          description: Id of account to fetch
          required: true
          type: string
      responses:
        200:
          description: return account
          schema:
            $ref: Account
            
definitions:
  Bank:
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      totalDeposits:
        type: string
  Account:
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      balance:
        type: string
